server:
  port: 7001

eureka:
  instance:
    # Eureka服务端的实例名称
    hostname: localhost
  # 自定义集群的hostname和port
  cluster:
    hostname:
      - test
    port:
      - 7002
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示白己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.cluster.hostname[0]}:${eureka.cluster.port[0]}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
