server:
  port: 3344

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Didnelpsun/SpringCloud.git

eureka:
  instance:
    instance-id: config3344
    prefer-ip-address: true
  client:
    # true表示向注册中心注册自己，因为这是业务模块
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
