server:
  port: 8801

spring:
  application:
    name: provider
  # 配置RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    # 自定义通道名称
    # 输出通道名称，即该服务器是发送消息的
    # 应该以通道名-out/in-序号表示
    # out表示这是个消息发送者
    name: provider-out-0
    stream:
      # 服务整合处理器
      bindings:
        ${spring.cloud.name}:
          # 使用的交换机或交换机的名称
          destination: defaultExchange
          # 消息类型
          contentType: application/json

eureka:
  instance:
    instance-id: provider8801
    prefer-ip-address: true
  client:
    # true表示向注册中心注册自己，因为这是业务模块
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

