server:
  # 客户端默认会访问80的端口
  port: 83

spring:
  application:
    name: order83
  cloud:
    consul:
      host: localhost
      port: 8500
      # 注册到Consul中
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

remote:
  url: http://localhost
  port: 8004