server:
  # 客户端默认会访问80的端口
  port: 93

spring:
  main:
    # 否则报错：The bean 'PAY.FeignClientSpecification' could not be registered. A bean with that name has already been defined and overriding is disabled.
    allow-bean-definition-overriding: true
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel Dashboard前端控制台地址
        dashboard: localhost:8080
        # 监控服务端口，默认为8719，如果占用就依次加一扫描
        port: 8719
      web-context-unify: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  # 开启Sentinel支持
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000

logging:
  level:
    org.didnelpsun.service.IPayService: debug
