server:
  port: 8004

spring:
  application:
    name: pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: root
  # 配置Consul
  cloud:
    consul:
      host: localhost
      port: 8500
      # 注册到Consul中
      discovery:
        hostname: localhost
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        prefer-ip-address: true

mybatis:
  # 定义实体类所在的包
  type-aliases-package: org.didnelpsun.entity
  mapper-locations: classpath:mapper/*.xml

