server:
  port: 9002

spring:
  application:
    name: pay
  cloud:
    nacos:
      discovery:
        server-addr: localhost:85

management:
  endpoints:
    web:
      exposure:
        include: '*'